name: C++11 Compatibility Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    list:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - id: set-matrix
              run: |
                echo "::set-output name=matrix::{\"sketch\": $(find examples -name '*.ino' | jq -R -s -c 'split("\n") | map(select(length > 0))')}"

    build:
        needs: list
        runs-on: ubuntu-latest
        strategy:
            matrix:
                sketch: ${{fromJson(needs.list.outputs.matrix).sketch}}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install cppcheck
              run: sudo apt-get install cppcheck
            
            - name: Run cppcheck (C++11) on ${{ matrix.sketch }}
              run: |
                    cppcheck --enable=all \
                                     --std=c++11 \
                                     --language=c++ \
                                     --suppress=unusedFunction:setup \
                                     --suppress=unusedFunction:loop \
                                     ${{ matrix.sketch }}