name: C++11 Compatibility Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: C++11 Compatibility Check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install cppcheck
              run: sudo apt-get install cppcheck
            
            - name: Run cppcheck (C++11)
              run: cppcheck --enable=all --std=c++11 --language=c++ --suppress=unusedFunction:*/setup --suppress=unusedFunction:*/loop examples/AdvancedUSBInternalOperations/AdvancedUSBInternalOperations.ino